#ifndef PROTOCOL_COMMAND_TYPES_H
#define PROTOCOL_COMMAND_TYPES_H

// Enum CommandType for all FTP commands
enum class CommandType {
    USER, PASS, QUIT, NOOP, PWD, CWD, CDUP, MKD, RMD, LIST, NLST, STAT, SIZE, MDTM, TYPE, MODE, PORT, PASV, RETR, STOR, STOU, APPE, DELE, RNFR, RNTO, HASH, ABOR, HELP, UNKNOWN
};
#endif // PROTOCOL_COMMAND_TYPES_H
